export {
  LayoutDashboard as OverviewIcon,
  Package as ProductIcon,
  Handshake as CounterpartyIcon,
  ArchiveRestore as PurchaseIcon,
  Truck as SalesIcon,
  FileSpreadsheet as QuoteIcon,
  FileCheck2 as ContractIcon,
  DatabaseBackup as BackupIcon,
  Search as SearchIcon,
  CircleUserRound as AccountIcon,
  LogOut as LogoutIcon,
  CalendarDays as CalendarIcon,
  CloudSun as WeatherIcon,
} from "lucide-react"
